; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = rp2350

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_metro_rp2350
framework = arduino
board_build.core = earlephilhower
custom_vl53l9_st_source = ../STMicro_source/STM32CubeExpansion_53L9A1_V1.0.0/Drivers/BSP/Components/vl53l9
build_flags =
    -DVL53L9_HOST_XSHUT_PIN=0
    -DVL53L9_HOST_INTR_PIN=1
    -DVL53L9_HOST_CLKIN_PIN=11
    -DVL53L9_HOST_CLKIN_ENABLE=1
    -DVL53L9_HOST_CLKIN_HZ=12000000
    -DVL53L9_HOST_SYNCIN_PIN=44
    -DVL53L9_HOST_SYNCIN_ENABLE=1
    -DVL53L9_I3C_SDA_PIN=20
    -DVL53L9_I3C_SCL_PIN=21
    -DVL53L9_I3C_PIO_INDEX=0
    -DVL53L9_I3C_SM=1
    -DVL53L9_I3C_DRIVE_STRENGTH_MA=12
    -DVL53L9_I3C_CLK_KHZ=1000
    -DVL53L9_I3C_DISABLE_INTERRUPTS=0
    -DVL53L9_I3C_DYNAMIC_ADDRESS=0x52
    -DVL53L9_RANGING_SYNC_MODE=VL53L9_SYNC_AUTONOMOUS
    -DVL53L9_RANGING_POWER_MODE=VL53L9_POWER_REGULAR
    -DVL53L9_RANGING_CONTEXT=VL53L9_CONTEXT_SHORT
    -DVL53L9_RANGING_BINNING=12
    -DVL53L9_RANGING_FRAME_PERIOD_US=250000
    -DVL53L9_RANGING_EXPOSURE_MS=5
    -DVL53L9_RANGING_SAMPLE_COUNT=3
    -DVL53L9_RANGING_FRAME_TIMEOUT_MS=2000
    -DVL53L9_RANGING_FRAME_POLL_INTERVAL_MS=5
    -DVL53L9_RANGING_FRAME_WAIT_MODE=VL53L9CX_FRAME_WAIT_POLL
extra_scripts =
    pre:scripts/gen_i3c_pio.py
    pre:scripts/gen_st_vl53l9.py

[env:rp2350]
lib_ignore =
    vl53l9_arduino
    VL53L9CX_Arduino
build_flags =
    ${env.build_flags}
    -DVL53L9_ENABLE_ST_DRIVER=0
    -DVL53L9_ENABLE_RANGING_SAMPLE=0

[env:rp2350_st_driver]
build_flags =
    ${env.build_flags}
    -DVL53L9_ENABLE_ST_DRIVER=1
    -DVL53L9_ENABLE_RANGING_SAMPLE=1
