; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rp2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
build_flags =
    -DVL53L9_I3C_SDA_PIN=16
    -DVL53L9_I3C_SCL_PIN=17
    -DVL53L9_I3C_PIO_INDEX=0
    -DVL53L9_I3C_SM=1
    -DVL53L9_I3C_DRIVE_STRENGTH_MA=12
    -DVL53L9_I3C_CLK_KHZ=1000
    -DVL53L9_I3C_DISABLE_INTERRUPTS=1
extra_scripts =
    pre:scripts/gen_i3c_pio.py
